name: Test run buildout

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.7", "3.8", "3.9"]
        plone: ["52"]
        # exclude:
        #   - python: "3.7"
        #     plone: "51"
    steps:
      - uses: actions/checkout@v1
      - name: Cache eggs
        uses: actions/cache@v1
        with:
          path: eggs
          key: ${{ runner.OS }}-build-python${{ matrix.python }}-${{ matrix.plone }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          ln -s ./profiles/production.cfg production.cfg
          ln -s ./profiles/staging.cfg staging.cfg
          ln -s ./profiles/development.cfg development.cfg
      - name: Install production
        run: |
          buildout -Nc production.cfg -t 3
      - name: Install staging
        run: |
          buildout -Nc staging.cfg -t 3
      - name: Install development
        run: |
          buildout -Nc development.cfg -t 3
  build:
    runs-on: self-hosted
    steps:
      - name: setup pyenv
        uses: "gabrielfalcao/pyenv-action@v5"
      - name: run buildout
        run: |
          cd ${BUILDOUT_PATH} && buildout -N
