name: Test run buildout

on: [push]

jobs:
  prova:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":[{\"label\":\"foo\"},{\"label\":\"bar\"}]}"
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.7", "3.8", "3.9"]
        plone: ["52"]
        # exclude:
        #   - python: "3.7"
        #     plone: "51"
    steps:
      - uses: actions/checkout@v1
      - name: Cache eggs
        uses: actions/cache@v1
        with:
          path: eggs
          key: ${{ runner.OS }}-build-python${{ matrix.python }}-${{ matrix.plone }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          ln -s ./profiles/production.cfg production.cfg
          ln -s ./profiles/staging.cfg staging.cfg
          ln -s ./profiles/development.cfg development.cfg
      - name: Install production
        run: |
          buildout -Nc production.cfg -t 3
      - name: Install staging
        run: |
          buildout -Nc staging.cfg -t 3
      - name: Install development
        run: |
          buildout -Nc development.cfg -t 4
  build:
    needs: prova
    strategy:
      matrix: ${{fromJson(needs.prova.outputs.matrix)}}
    runs-on: self-hosted
    steps:
      - name: run buildout
        run: |
          # cd ${BUILDOUT_PATH} && ./bin/develop rb
          echo "QUI: ${BUILDOUT_PATH}"
          echo ${{ matrix.label }}
